general:
  bot_token: "8430579911:AAHDWHzplanvW4FyvGr0HPqBKbvutMCd_fU"
  language: "zh-hans"
  worker_num: 3
  download_worker_num: 4
  admin_uid: 8334035740
  user_daily_limit: 0
  process_wait_queue_max_size: 50
  process_timeout: 60
  support_tgs_file: false
  max_amount_per_req: 1000

community:
  enable: true
  force_channel_sub: true
  reward_on_sub: true
  channel:
    username: "@ChisaSama"
  reward:
    extra_download_times: 100

cache:
  enabled: true
  storage_dir: "/apps/StickerDownloader/data/storage/"
  max_disk_usage: 1024
  cache_expire: 604800
  cache_clean_interval: 3600

logger:
  report: false
  report_url: ""
  report_query_key: ""

redis:
  server: "192.168.11.2"
  port: "6379"
  tls: false
  password: "Srysx110723/"
  db: 1

proxy:
  enabled: true
  server: "90.156.213.59"
  port: "443"
  secret: "dd6b3fb02424dbac55fef2da67c8c949"